-- Extended profile fields for Profile Edit: interests, causes, work, education, lifestyle, custody, etc.
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS interests TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS causes TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS qualities TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS profession TEXT,
  ADD COLUMN IF NOT EXISTS company TEXT,
  ADD COLUMN IF NOT EXISTS studies TEXT,
  ADD COLUMN IF NOT EXISTS school TEXT,
  ADD COLUMN IF NOT EXISTS hometown TEXT,
  ADD COLUMN IF NOT EXISTS hometown_country TEXT,
  ADD COLUMN IF NOT EXISTS sexuality TEXT,
  ADD COLUMN IF NOT EXISTS religion TEXT,
  ADD COLUMN IF NOT EXISTS politics TEXT,
  ADD COLUMN IF NOT EXISTS star_sign TEXT,
  ADD COLUMN IF NOT EXISTS height INTEGER,
  ADD COLUMN IF NOT EXISTS weight INTEGER,
  ADD COLUMN IF NOT EXISTS exercise TEXT,
  ADD COLUMN IF NOT EXISTS drinking TEXT,
  ADD COLUMN IF NOT EXISTS smoking TEXT,
  ADD COLUMN IF NOT EXISTS cannabis TEXT,
  ADD COLUMN IF NOT EXISTS drugs TEXT,
  ADD COLUMN IF NOT EXISTS diet TEXT,
  ADD COLUMN IF NOT EXISTS vaccinated TEXT,
  ADD COLUMN IF NOT EXISTS children JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS eye_colour TEXT,
  ADD COLUMN IF NOT EXISTS hair_colour TEXT,
  ADD COLUMN IF NOT EXISTS blood_type TEXT,
  ADD COLUMN IF NOT EXISTS pets TEXT,
  ADD COLUMN IF NOT EXISTS relationship_status TEXT,
  ADD COLUMN IF NOT EXISTS household_situation TEXT,
  ADD COLUMN IF NOT EXISTS family_situation TEXT,
  ADD COLUMN IF NOT EXISTS custody_school_arrangement TEXT,
  ADD COLUMN IF NOT EXISTS custody_school_days TEXT,
  ADD COLUMN IF NOT EXISTS custody_vacation_arrangement TEXT,
  ADD COLUMN IF NOT EXISTS custody_vacation_conditions TEXT,
  ADD COLUMN IF NOT EXISTS custody_further_info TEXT,
  ADD COLUMN IF NOT EXISTS conception_methods TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS parenting_philosophy TEXT,
  ADD COLUMN IF NOT EXISTS financial_situation TEXT,
  ADD COLUMN IF NOT EXISTS lifestyle_rhythm TEXT;
